server:
  port: 8888
#  servlet:     # breaks playground
#    context-path: "/api"

spring:
  application:
    name: Java GraphQL Microservice
    version: 0.1
    description: A Spring Boot Microservice application exposing both REST and GraphQL endpoints
  data:
    mongodb:
      authentication-database: admin
      database: graph_ql_db
      username: mongo_user
      password: my_very_secret_mongo_password
      host: docker-mongo
      port: 27017
  main:
    banner-mode: off

developer:
  name: cookieMr
  email: mr@cookie.inc
  url: https://github.com/cookieMr

management:
  endpoints:
    enabled-by-default: false

graphql:
  servlet:
    exception-handlers-enabled: true
    tracingEnabled: true
